sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t daenamkim/frontend -f Dockerfile.dev .

script:
  - docker run --env CI=true daenamkim/frontend yarn test --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-007281231765"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

