sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t daenamkim/frontend -f Dockerfile.dev .

script:
  - cd frontend
  - docker run daenamkim/frontend -- --coverage
