sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t daenamkim/frontend -f Dockerfile.dev .

script:
  - docker run --env CI=true daenamkim/frontend yarn test --coverage
